### ISSUE TITLE
Informasi tambahan

### ISSUE THREAD

**Issue by FachrulCH** [kuntoaji/learnkotlin#1]
Coba ini juga mpek, bagus buat belajar kotlin https://play.kotlinlang.org/koans/overview
Lebih cihui belajar di koans, macam TDD

**Comment by kuntoaji** [comment]
mantap bro..

**Comment by FachrulCH** [comment]
gw bikin PR nya apah? ahaha :D

**Comment by kuntoaji** [comment]
gass bro...
